services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: consignadohub-sqlserver
    environment:
      SA_PASSWORD: "ConsignadoHub!2026"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1444:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - consignadohub
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "ConsignadoHub!2026" -Q "SELECT 1" -No
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    container_name: consignadohub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: consignadohub
      RABBITMQ_DEFAULT_PASS: "ConsignadoHub!2026"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - consignadohub
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlserver-data:
  rabbitmq-data:


networks:
  consignadohub:
    driver: bridge
